# CLI Utilities
brew 'git'
brew 'tig'
brew 'n'
brew 'node'
brew 'npm'
brew 'yarn'
brew 'wifi-password'
brew 'youtube-dl'

# Apps
brew install --cask 'google-chrome'
brew install --cask 'firefox'
brew install --cask 'dropbox'
brew install --cask 'slack'
brew install --cask 'skype'
brew install --cask 'sketch'
brew install --cask 'zeplin'
brew install --cask 'figma'
brew install --cask 'expo-xde'
brew install --cask 'iterm2'
brew install --cask 'visual-studio-code'
brew install --cask 'sublime-text'
brew install --cask 'postman'
brew install --cask 'spectacle'
brew install --cask 'arduino'

brew install --cask 'microsoft-office'
brew install --cask 'adobe-creative-cloud'
brew install --cask 'the-unarchiver'
brew install --cask 'appcleaner'
brew install --cask 'keepingyouawake'
brew install --cask 'little-snitch'
brew install --cask 'micro-snitch'

brew install --cask 'vlc'
brew install --cask 'spotify'
brew install --cask 'discord'
brew install --cask 'spotmenu'

# System Plugins
brew install --cask 'qlcolorcode'
brew install --cask 'qlstephen'
brew install --cask 'qlmarkdown'
brew install --cask 'quicklook-json'
brew install --cask 'qlprettypatch'
brew install --cask 'quicklook-csv'
brew install --cask 'betterzipql'
brew install --cask 'webpquicklook'
